name: Pre-release Notes

on:
  release:
    types: [published]

jobs:
  uv-example:
    name: Generate Release Notes
    runs-on: ubuntu-latest

    steps:
      # Checkout the current repo (optional if script is in the same repo)
      - uses: actions/checkout@v4

      # Clone the gha_jira_sync repo
      - name: Clone gha_jira_sync
        run: |
          git clone https://github.com/OliveraReeves/gha_jira_sync.git
          cd gha_jira_sync
          # Optional: check out a specific branch or tag
          # git checkout main

      # Set up Python environment using uv
      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Set up Python
        run: uv python install

      # Install your gha_jira_sync package
      - name: Install gha_jira_sync
        run: |
          cd gha_jira_sync
          pip install .

      # Run the generate_release_notes.py script
      - name: Run Ticket Script
        id: tickets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd gha_jira_sync
          RELEASE_NOTES=$(python scripts/generate_release_notes.py --repo-url https://github.com/renalreg/webapi)
          echo "release_notes<<EOF" >> $GITHUB_OUTPUT
          echo "$RELEASE_NOTES" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      # Update release description with Markdown
      - name: Update GitHub Release
        uses: actions-ecosystem/action-update-release@v1
        with:
          tag: ${{ github.event.release.tag_name }}
          body: ${{ steps.tickets.outputs.release_notes }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
