name: Pre-release Notes

on:
  release:
    types: [published]

jobs:
  uv-example:
    name: Generate Release Notes
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Clone gha_jira_sync
        run: |
          git clone https://github.com/OliveraReeves/gha_jira_sync.git
          cd gha_jira_sync

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Set up Python
        run: uv python install

      - name: Install gha_jira_sync
        run: |
          cd gha_jira_sync
          pip install .

      - name: Run Ticket Script
        id: tickets
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
        run: |
          cd gha_jira_sync
          RELEASE_NOTES=$(python scripts/generate_release_notes.py --repo-url https://github.com/renalreg/webapi)
          {
            echo "release_notes<<EOF"
            cat release_notes.txt
            echo "EOF"
          } >> $GITHUB_OUTPUT

      - name: Update GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.release.tag_name }}
          name: ${{ github.event.release.name }}
          body: |
            ${{ github.event.release.body }}

            ${{ steps.tickets.outputs.release_notes }}
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
